sonar.projectKey=smartproperty-frontend-properties
sonar.projectName=SmartProperty Frontend - Properties Pages
sonar.sources=src
sonar.inclusions=src/pages/BuyDetails.jsx,src/pages/BuyPropertyList.jsx,src/pages/RentPropertyList.jsx,src/pages/RentDetails.jsx
sonar.host.url=http://localhost:9000
sonar.token=squ_11af45207ea00436eae321d4dc9fd222f3246569
sonar.sourceEncoding=UTF-8
sonar.issue.ignore.multicriteria=f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15
sonar.issue.ignore.multicriteria.f1.ruleKey=javascript:S7764
sonar.issue.ignore.multicriteria.f1.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f2.ruleKey=javascript:S6844
sonar.issue.ignore.multicriteria.f2.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f3.ruleKey=javascript:S6819
sonar.issue.ignore.multicriteria.f3.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f4.ruleKey=javascript:S7781
sonar.issue.ignore.multicriteria.f4.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f5.ruleKey=javascript:S7735
sonar.issue.ignore.multicriteria.f5.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f6.ruleKey=javascript:S6772
sonar.issue.ignore.multicriteria.f6.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f7.ruleKey=javascript:S3358
sonar.issue.ignore.multicriteria.f7.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f8.ruleKey=javascript:S7773
sonar.issue.ignore.multicriteria.f8.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f9.ruleKey=javascript:S6582
sonar.issue.ignore.multicriteria.f9.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f10.ruleKey=javascript:S6774
sonar.issue.ignore.multicriteria.f10.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f11.ruleKey=javascript:S6749
sonar.issue.ignore.multicriteria.f11.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f12.ruleKey=javascript:S6479
sonar.issue.ignore.multicriteria.f12.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f13.ruleKey=javascript:S7723
sonar.issue.ignore.multicriteria.f13.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f14.ruleKey=javascript:S6638
sonar.issue.ignore.multicriteria.f14.resourceKey=src/pages/*.jsx
sonar.issue.ignore.multicriteria.f15.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.f15.resourceKey=src/pages/*.jsx
