sonar.projectKey=smartproperty-backend-properties
sonar.projectName=SmartProperty Backend - Properties Module
sonar.sources=src
sonar.inclusions=src/models/Property.js,src/controllers/propertyController.js,src/routes/property.routes.js
sonar.host.url=http://localhost:9000
sonar.token=squ_11af45207ea00436eae321d4dc9fd222f3246569
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info