# sonar.projectKey=smartproperty-backoffice-properties
# sonar.projectName=SmartProperty Backoffice - Properties Pages
# sonar.sources=src
# sonar.inclusions=src/pages/MyProperties.tsx,src/pages/PropertyDetails.tsx
# sonar.sourceEncoding=UTF-8
# sonar.host.url=http://localhost:9000
# sonar.token=squ_11af45207ea00436eae321d4dc9fd222f3246569
# sonar.issue.ignore.multicriteria=b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,b12
# sonar.issue.ignore.multicriteria.b1.ruleKey=typescript:S6853
# sonar.issue.ignore.multicriteria.b1.resourceKey=src/pages/*.tsx
# sonar.issue.ignore.multicriteria.b2.ruleKey=typescript:S7773
# sonar.issue.ignore.multicriteria.b2.resourceKey=src/pages/*.tsx
# sonar.issue.ignore.multicriteria.b3.ruleKey=typescript:S7735
# sonar.issue.ignore.multicriteria.b3.resourceKey=src/pages/*.tsx
# sonar.issue.ignore.multicriteria.b4.ruleKey=typescript:S3358
# sonar.issue.ignore.multicriteria.b4.resourceKey=src/pages/*.tsx
# sonar.issue.ignore.multicriteria.b5.ruleKey=typescript:S3776
# sonar.issue.ignore.multicriteria.b5.resourceKey=src/pages/*.tsx
# sonar.issue.ignore.multicriteria.b6.ruleKey=typescript:S6772
# sonar.issue.ignore.multicriteria.b6.resourceKey=src/pages/*.tsx
# sonar.issue.ignore.multicriteria.b7.ruleKey=typescript:S6759
# sonar.issue.ignore.multicriteria.b7.resourceKey=src/pages/*.tsx
# sonar.issue.ignore.multicriteria.b8.ruleKey=typescript:S6582
# sonar.issue.ignore.multicriteria.b8.resourceKey=src/pages/*.tsx
# sonar.issue.ignore.multicriteria.b9.ruleKey=typescript:S4323
# sonar.issue.ignore.multicriteria.b9.resourceKey=src/pages/*.tsx
# sonar.issue.ignore.multicriteria.b10.ruleKey=typescript:S2004
# sonar.issue.ignore.multicriteria.b10.resourceKey=src/pages/*.tsx
# sonar.issue.ignore.multicriteria.b11.ruleKey=typescript:S4624
# sonar.issue.ignore.multicriteria.b11.resourceKey=src/pages/*.tsx
# sonar.issue.ignore.multicriteria.b12.ruleKey=typescript:S6551
# sonar.issue.ignore.multicriteria.b12.resourceKey=src/pages/*.tsx
